/*
###############################################################
#  Generated by:      Cadence Innovus 20.15-s105_1
#  OS:                Linux x86_64(Host ID yukari.ecen.okstate.edu)
#  Generated on:      Wed Nov 16 13:38:36 2022
#  Design:            gcd
#  Command:           saveNetlist -excludeLeafCell final.v
###############################################################
*/
module gcd (
	clk, 
	req_msg, 
	req_rdy, 
	req_val, 
	reset, 
	resp_msg, 
	resp_rdy, 
	resp_val);
   input clk;
   input [31:0] req_msg;
   output req_rdy;
   input req_val;
   input reset;
   output [15:0] resp_msg;
   input resp_rdy;
   output resp_val;

   // Internal wires
   wire N45;
   wire n193;
   wire n194;
   wire n195;
   wire n196;
   wire n197;
   wire n198;
   wire n199;
   wire n200;
   wire n201;
   wire n202;
   wire n203;
   wire n204;
   wire n205;
   wire n206;
   wire n207;
   wire n208;
   wire n209;
   wire n210;
   wire n211;
   wire n212;
   wire n213;
   wire n214;
   wire n215;
   wire n216;
   wire n217;
   wire n218;
   wire n219;
   wire n220;
   wire n221;
   wire n222;
   wire n223;
   wire n224;
   wire \intadd_0/SUM[6] ;
   wire \intadd_0/SUM[5] ;
   wire \intadd_0/SUM[4] ;
   wire \intadd_0/SUM[3] ;
   wire \intadd_0/SUM[2] ;
   wire \intadd_0/SUM[1] ;
   wire \intadd_0/SUM[0] ;
   wire \intadd_0/n8 ;
   wire \intadd_0/n7 ;
   wire \intadd_0/n6 ;
   wire \intadd_0/n5 ;
   wire \intadd_0/n4 ;
   wire \intadd_0/n3 ;
   wire \intadd_0/n2 ;
   wire \intadd_1/CI ;
   wire \intadd_1/SUM[6] ;
   wire \intadd_1/SUM[5] ;
   wire \intadd_1/SUM[4] ;
   wire \intadd_1/SUM[3] ;
   wire \intadd_1/SUM[2] ;
   wire \intadd_1/SUM[1] ;
   wire \intadd_1/SUM[0] ;
   wire \intadd_1/n7 ;
   wire \intadd_1/n6 ;
   wire \intadd_1/n5 ;
   wire \intadd_1/n4 ;
   wire \intadd_1/n3 ;
   wire \intadd_1/n2 ;
   wire \intadd_1/n1 ;
   wire n226;
   wire n227;
   wire n228;
   wire n230;
   wire n231;
   wire n232;
   wire n233;
   wire n234;
   wire n235;
   wire n236;
   wire n237;
   wire n238;
   wire n239;
   wire n240;
   wire n241;
   wire n242;
   wire n243;
   wire n244;
   wire n245;
   wire n246;
   wire n247;
   wire n248;
   wire n249;
   wire n250;
   wire n251;
   wire n252;
   wire n253;
   wire n254;
   wire n255;
   wire n256;
   wire n257;
   wire n258;
   wire n259;
   wire n260;
   wire n261;
   wire n262;
   wire n263;
   wire n264;
   wire n265;
   wire n266;
   wire n267;
   wire n268;
   wire n269;
   wire n270;
   wire n271;
   wire n272;
   wire n273;
   wire n274;
   wire n275;
   wire n276;
   wire n277;
   wire n278;
   wire n279;
   wire n280;
   wire n281;
   wire n282;
   wire n283;
   wire n284;
   wire n285;
   wire n286;
   wire n287;
   wire n288;
   wire n289;
   wire n290;
   wire n291;
   wire n292;
   wire n293;
   wire n294;
   wire n295;
   wire n296;
   wire n297;
   wire n299;
   wire n300;
   wire n301;
   wire n302;
   wire n303;
   wire n304;
   wire n305;
   wire n306;
   wire n307;
   wire n308;
   wire n309;
   wire n310;
   wire n311;
   wire n312;
   wire n313;
   wire n314;
   wire n315;
   wire n316;
   wire n317;
   wire n318;
   wire n319;
   wire n320;
   wire n321;
   wire n322;
   wire n323;
   wire n324;
   wire n325;
   wire n326;
   wire n327;
   wire n328;
   wire n329;
   wire n330;
   wire n331;
   wire n332;
   wire n333;
   wire n334;
   wire n335;
   wire n336;
   wire n337;
   wire n338;
   wire n339;
   wire n340;
   wire n341;
   wire n342;
   wire n343;
   wire n344;
   wire n345;
   wire n346;
   wire n347;
   wire n348;
   wire n349;
   wire n350;
   wire n351;
   wire n352;
   wire n353;
   wire n354;
   wire n355;
   wire n356;
   wire n357;
   wire n358;
   wire n359;
   wire n360;
   wire n361;
   wire n362;
   wire n363;
   wire n364;
   wire n365;
   wire n366;
   wire n367;
   wire n368;
   wire n369;
   wire n370;
   wire n371;
   wire n372;
   wire n373;
   wire n374;
   wire n375;
   wire n376;
   wire n377;
   wire n378;
   wire n379;
   wire n380;
   wire n381;
   wire n382;
   wire n383;
   wire n384;
   wire n385;
   wire n386;
   wire n387;
   wire n388;
   wire n389;
   wire [1:0] state$out;
   wire [15:0] b_reg$out;
   wire [15:0] a_reg$out;

   gf180mcu_osu_sc_9T_dff_1 \out_reg[15]1  (.Q(b_reg$out[15]),
	.QN(n245),
	.CLK(clk),
	.D(n224));
   gf180mcu_osu_sc_9T_dff_1 \out_reg[1]  (.Q(state$out[1]),
	.QN(n244),
	.CLK(clk),
	.D(N45));
   gf180mcu_osu_sc_9T_dff_1 \out_reg[0]  (.Q(state$out[0]),
	.QN(n242),
	.CLK(clk),
	.D(n250));
   gf180mcu_osu_sc_9T_dff_1 \out_reg[14]1  (.Q(b_reg$out[14]),
	.QN(n249),
	.CLK(clk),
	.D(n223));
   gf180mcu_osu_sc_9T_dff_1 \out_reg[1]2  (.Q(b_reg$out[1]),
	.QN(),
	.CLK(clk),
	.D(n222));
   gf180mcu_osu_sc_9T_dff_1 \out_reg[2]1  (.Q(b_reg$out[2]),
	.QN(),
	.CLK(clk),
	.D(n221));
   gf180mcu_osu_sc_9T_dff_1 \out_reg[3]1  (.Q(b_reg$out[3]),
	.QN(),
	.CLK(clk),
	.D(n220));
   gf180mcu_osu_sc_9T_dff_1 \out_reg[4]1  (.Q(b_reg$out[4]),
	.QN(),
	.CLK(clk),
	.D(n219));
   gf180mcu_osu_sc_9T_dff_1 \out_reg[5]1  (.Q(b_reg$out[5]),
	.QN(),
	.CLK(clk),
	.D(n218));
   gf180mcu_osu_sc_9T_dff_1 \out_reg[6]1  (.Q(b_reg$out[6]),
	.QN(),
	.CLK(clk),
	.D(n217));
   gf180mcu_osu_sc_9T_dff_1 \out_reg[7]1  (.Q(b_reg$out[7]),
	.QN(),
	.CLK(clk),
	.D(n216));
   gf180mcu_osu_sc_9T_dff_1 \out_reg[8]1  (.Q(b_reg$out[8]),
	.QN(),
	.CLK(clk),
	.D(n215));
   gf180mcu_osu_sc_9T_dff_1 \out_reg[9]1  (.Q(b_reg$out[9]),
	.QN(),
	.CLK(clk),
	.D(n214));
   gf180mcu_osu_sc_9T_dff_1 \out_reg[10]1  (.Q(b_reg$out[10]),
	.QN(),
	.CLK(clk),
	.D(n213));
   gf180mcu_osu_sc_9T_dff_1 \out_reg[11]1  (.Q(b_reg$out[11]),
	.QN(n248),
	.CLK(clk),
	.D(n212));
   gf180mcu_osu_sc_9T_dff_1 \out_reg[12]1  (.Q(b_reg$out[12]),
	.QN(n247),
	.CLK(clk),
	.D(n211));
   gf180mcu_osu_sc_9T_dff_1 \out_reg[13]1  (.Q(b_reg$out[13]),
	.QN(n246),
	.CLK(clk),
	.D(n210));
   gf180mcu_osu_sc_9T_dff_1 \out_reg[0]2  (.Q(b_reg$out[0]),
	.QN(),
	.CLK(clk),
	.D(n209));
   gf180mcu_osu_sc_9T_dff_1 \out_reg[14]  (.Q(a_reg$out[14]),
	.QN(n226),
	.CLK(clk),
	.D(n208));
   gf180mcu_osu_sc_9T_dff_1 \out_reg[1]1  (.Q(a_reg$out[1]),
	.QN(n227),
	.CLK(clk),
	.D(n207));
   gf180mcu_osu_sc_9T_dff_1 \out_reg[2]  (.Q(a_reg$out[2]),
	.QN(n238),
	.CLK(clk),
	.D(n206));
   gf180mcu_osu_sc_9T_dff_1 \out_reg[3]  (.Q(a_reg$out[3]),
	.QN(n240),
	.CLK(clk),
	.D(n205));
   gf180mcu_osu_sc_9T_dff_1 \out_reg[4]  (.Q(a_reg$out[4]),
	.QN(n228),
	.CLK(clk),
	.D(n204));
   gf180mcu_osu_sc_9T_dff_1 \out_reg[5]  (.Q(a_reg$out[5]),
	.QN(n231),
	.CLK(clk),
	.D(n203));
   gf180mcu_osu_sc_9T_dff_1 \out_reg[6]  (.Q(a_reg$out[6]),
	.QN(n233),
	.CLK(clk),
	.D(n202));
   gf180mcu_osu_sc_9T_dff_1 \out_reg[7]  (.Q(a_reg$out[7]),
	.QN(n234),
	.CLK(clk),
	.D(n201));
   gf180mcu_osu_sc_9T_dff_1 \out_reg[8]  (.Q(a_reg$out[8]),
	.QN(n239),
	.CLK(clk),
	.D(n200));
   gf180mcu_osu_sc_9T_dff_1 \out_reg[9]  (.Q(a_reg$out[9]),
	.QN(n237),
	.CLK(clk),
	.D(n199));
   gf180mcu_osu_sc_9T_dff_1 \out_reg[10]  (.Q(a_reg$out[10]),
	.QN(n236),
	.CLK(clk),
	.D(n198));
   gf180mcu_osu_sc_9T_dff_1 \out_reg[11]  (.Q(a_reg$out[11]),
	.QN(n235),
	.CLK(clk),
	.D(n197));
   gf180mcu_osu_sc_9T_dff_1 \out_reg[12]  (.Q(a_reg$out[12]),
	.QN(n241),
	.CLK(clk),
	.D(n196));
   gf180mcu_osu_sc_9T_dff_1 \out_reg[13]  (.Q(a_reg$out[13]),
	.QN(n230),
	.CLK(clk),
	.D(n195));
   gf180mcu_osu_sc_9T_dff_1 \out_reg[0]1  (.Q(a_reg$out[0]),
	.QN(n232),
	.CLK(clk),
	.D(n194));
   gf180mcu_osu_sc_9T_dff_1 \out_reg[15]  (.Q(a_reg$out[15]),
	.QN(n243),
	.CLK(clk),
	.D(n193));
   gf180mcu_osu_sc_9T_addf_1 \intadd_0/U9  (.CO(\intadd_0/n8 ),
	.S(\intadd_0/SUM[0] ),
	.A(n239),
	.B(b_reg$out[8]),
	.CI(\intadd_1/n1 ));
   gf180mcu_osu_sc_9T_addf_1 \intadd_0/U8  (.CO(\intadd_0/n7 ),
	.S(\intadd_0/SUM[1] ),
	.A(n237),
	.B(b_reg$out[9]),
	.CI(\intadd_0/n8 ));
   gf180mcu_osu_sc_9T_addf_1 \intadd_0/U7  (.CO(\intadd_0/n6 ),
	.S(\intadd_0/SUM[2] ),
	.A(n236),
	.B(b_reg$out[10]),
	.CI(\intadd_0/n7 ));
   gf180mcu_osu_sc_9T_addf_1 \intadd_0/U6  (.CO(\intadd_0/n5 ),
	.S(\intadd_0/SUM[3] ),
	.A(n235),
	.B(b_reg$out[11]),
	.CI(\intadd_0/n6 ));
   gf180mcu_osu_sc_9T_addf_1 \intadd_0/U5  (.CO(\intadd_0/n4 ),
	.S(\intadd_0/SUM[4] ),
	.A(n241),
	.B(b_reg$out[12]),
	.CI(\intadd_0/n5 ));
   gf180mcu_osu_sc_9T_addf_1 \intadd_0/U4  (.CO(\intadd_0/n3 ),
	.S(\intadd_0/SUM[5] ),
	.A(n230),
	.B(b_reg$out[13]),
	.CI(\intadd_0/n4 ));
   gf180mcu_osu_sc_9T_addf_1 \intadd_0/U3  (.CO(\intadd_0/n2 ),
	.S(\intadd_0/SUM[6] ),
	.A(n226),
	.B(b_reg$out[14]),
	.CI(\intadd_0/n3 ));
   gf180mcu_osu_sc_9T_addf_1 \intadd_1/U8  (.CO(\intadd_1/n7 ),
	.S(\intadd_1/SUM[0] ),
	.A(n227),
	.B(b_reg$out[1]),
	.CI(\intadd_1/CI ));
   gf180mcu_osu_sc_9T_addf_1 \intadd_1/U7  (.CO(\intadd_1/n6 ),
	.S(\intadd_1/SUM[1] ),
	.A(n238),
	.B(b_reg$out[2]),
	.CI(\intadd_1/n7 ));
   gf180mcu_osu_sc_9T_addf_1 \intadd_1/U6  (.CO(\intadd_1/n5 ),
	.S(\intadd_1/SUM[2] ),
	.A(n240),
	.B(b_reg$out[3]),
	.CI(\intadd_1/n6 ));
   gf180mcu_osu_sc_9T_addf_1 \intadd_1/U5  (.CO(\intadd_1/n4 ),
	.S(\intadd_1/SUM[3] ),
	.A(n228),
	.B(b_reg$out[4]),
	.CI(\intadd_1/n5 ));
   gf180mcu_osu_sc_9T_addf_1 \intadd_1/U4  (.CO(\intadd_1/n3 ),
	.S(\intadd_1/SUM[4] ),
	.A(n231),
	.B(b_reg$out[5]),
	.CI(\intadd_1/n4 ));
   gf180mcu_osu_sc_9T_addf_1 \intadd_1/U3  (.CO(\intadd_1/n2 ),
	.S(\intadd_1/SUM[5] ),
	.A(n233),
	.B(b_reg$out[6]),
	.CI(\intadd_1/n3 ));
   gf180mcu_osu_sc_9T_addf_1 \intadd_1/U2  (.CO(\intadd_1/n1 ),
	.S(\intadd_1/SUM[6] ),
	.A(n234),
	.B(b_reg$out[7]),
	.CI(\intadd_1/n2 ));
   gf180mcu_osu_sc_9T_and2_1 U230 (.Y(resp_val),
	.A(n242),
	.B(state$out[1]));
   gf180mcu_osu_sc_9T_and2_1 U231 (.Y(n250),
	.A(n285),
	.B(n282));
   gf180mcu_osu_sc_9T_nor2_1 U232 (.Y(req_rdy),
	.A(state$out[1]),
	.B(state$out[0]));
   gf180mcu_osu_sc_9T_or2_1 U233 (.Y(n251),
	.A(b_reg$out[12]),
	.B(b_reg$out[14]));
   gf180mcu_osu_sc_9T_or2_1 U234 (.Y(n252),
	.A(b_reg$out[10]),
	.B(n251));
   gf180mcu_osu_sc_9T_or2_1 U235 (.Y(n253),
	.A(b_reg$out[11]),
	.B(n252));
   gf180mcu_osu_sc_9T_nor2_1 U236 (.Y(n255),
	.A(b_reg$out[1]),
	.B(n253));
   gf180mcu_osu_sc_9T_nor2_1 U237 (.Y(n254),
	.A(b_reg$out[13]),
	.B(b_reg$out[15]));
   gf180mcu_osu_sc_9T_nand2_1 U238 (.Y(n280),
	.A(n255),
	.B(n254));
   gf180mcu_osu_sc_9T_nand2_1 U239 (.Y(n270),
	.A(b_reg$out[15]),
	.B(n243));
   gf180mcu_osu_sc_9T_nand2_1 U240 (.Y(n256),
	.A(a_reg$out[15]),
	.B(n245));
   gf180mcu_osu_sc_9T_oai21_1 U241 (.Y(n269),
	.A0(b_reg$out[14]),
	.A1(n226),
	.B(n256));
   gf180mcu_osu_sc_9T_nand2_1 U242 (.Y(n257),
	.A(n247),
	.B(a_reg$out[12]));
   gf180mcu_osu_sc_9T_addf_1 U243 (.CO(n267),
	.S(),
	.A(b_reg$out[13]),
	.B(n230),
	.CI(n257));
   gf180mcu_osu_sc_9T_aoi21_1 U244 (.Y(n262),
	.A0(b_reg$out[11]),
	.A1(n235),
	.B(b_reg$out[10]));
   gf180mcu_osu_sc_9T_addf_1 U245 (.CO(n258),
	.S(),
	.A(b_reg$out[8]),
	.B(\intadd_1/n1 ),
	.CI(n239));
   gf180mcu_osu_sc_9T_addf_1 U246 (.CO(n259),
	.S(),
	.A(b_reg$out[9]),
	.B(n258),
	.CI(n237));
   gf180mcu_osu_sc_9T_aoi21_1 U247 (.Y(n260),
	.A0(b_reg$out[10]),
	.A1(n236),
	.B(n259));
   gf180mcu_osu_sc_9T_addf_1 U248 (.CO(n261),
	.S(),
	.A(a_reg$out[11]),
	.B(n260),
	.CI(n248));
   gf180mcu_osu_sc_9T_aoi21_1 U249 (.Y(n263),
	.A0(a_reg$out[10]),
	.A1(n262),
	.B(n261));
   gf180mcu_osu_sc_9T_aoi21_1 U250 (.Y(n264),
	.A0(b_reg$out[12]),
	.A1(n241),
	.B(n263));
   gf180mcu_osu_sc_9T_oai21_1 U251 (.Y(n266),
	.A0(a_reg$out[13]),
	.A1(n246),
	.B(n264));
   gf180mcu_osu_sc_9T_oai21_1 U252 (.Y(n265),
	.A0(a_reg$out[14]),
	.A1(n249),
	.B(n270));
   gf180mcu_osu_sc_9T_aoi21_1 U253 (.Y(n268),
	.A0(n267),
	.A1(n266),
	.B(n265));
   gf180mcu_osu_sc_9T_aoi21_1 U254 (.Y(n290),
	.A0(n270),
	.A1(n269),
	.B(n268));
   gf180mcu_osu_sc_9T_nand2_1 U255 (.Y(n288),
	.A(n244),
	.B(state$out[0]));
   gf180mcu_osu_sc_9T_or2_1 U256 (.Y(n271),
	.A(n290),
	.B(n288));
   gf180mcu_osu_sc_9T_or2_1 U257 (.Y(n380),
	.A(b_reg$out[0]),
	.B(n271));
   gf180mcu_osu_sc_9T_or2_1 U258 (.Y(n272),
	.A(b_reg$out[5]),
	.B(b_reg$out[4]));
   gf180mcu_osu_sc_9T_or2_1 U259 (.Y(n273),
	.A(b_reg$out[2]),
	.B(n272));
   gf180mcu_osu_sc_9T_or2_1 U260 (.Y(n277),
	.A(b_reg$out[3]),
	.B(n273));
   gf180mcu_osu_sc_9T_or2_1 U261 (.Y(n274),
	.A(b_reg$out[9]),
	.B(b_reg$out[8]));
   gf180mcu_osu_sc_9T_or2_1 U262 (.Y(n275),
	.A(b_reg$out[6]),
	.B(n274));
   gf180mcu_osu_sc_9T_or2_1 U263 (.Y(n276),
	.A(b_reg$out[7]),
	.B(n275));
   gf180mcu_osu_sc_9T_or2_1 U264 (.Y(n278),
	.A(n277),
	.B(n276));
   gf180mcu_osu_sc_9T_or2_1 U265 (.Y(n279),
	.A(n380),
	.B(n278));
   gf180mcu_osu_sc_9T_or2_1 U266 (.Y(n285),
	.A(n280),
	.B(n279));
   gf180mcu_osu_sc_9T_nand2_1 U267 (.Y(n281),
	.A(req_val),
	.B(req_rdy));
   gf180mcu_osu_sc_9T_aoi21_1 U268 (.Y(n282),
	.A0(n242),
	.A1(n281),
	.B(reset));
   gf180mcu_osu_sc_9T_nand2_1 U269 (.Y(n283),
	.A(n232),
	.B(b_reg$out[0]));
   gf180mcu_osu_sc_9T_clkinv_1 U270 (.Y(\intadd_1/CI ),
	.A(n283));
   gf180mcu_osu_sc_9T_xor2_1 U271 (.Y(n284),
	.A(a_reg$out[15]),
	.B(b_reg$out[15]));
   gf180mcu_osu_sc_9T_xor2_1 U272 (.Y(resp_msg[15]),
	.A(n284),
	.B(\intadd_0/n2 ));
   gf180mcu_osu_sc_9T_clkinv_1 U274 (.Y(resp_msg[14]),
	.A(\intadd_0/SUM[6] ));
   gf180mcu_osu_sc_9T_clkinv_1 U275 (.Y(resp_msg[13]),
	.A(\intadd_0/SUM[5] ));
   gf180mcu_osu_sc_9T_clkinv_1 U276 (.Y(resp_msg[12]),
	.A(\intadd_0/SUM[4] ));
   gf180mcu_osu_sc_9T_clkinv_1 U277 (.Y(resp_msg[11]),
	.A(\intadd_0/SUM[3] ));
   gf180mcu_osu_sc_9T_clkinv_1 U278 (.Y(resp_msg[10]),
	.A(\intadd_0/SUM[2] ));
   gf180mcu_osu_sc_9T_clkinv_1 U279 (.Y(resp_msg[9]),
	.A(\intadd_0/SUM[1] ));
   gf180mcu_osu_sc_9T_clkinv_1 U280 (.Y(resp_msg[8]),
	.A(\intadd_0/SUM[0] ));
   gf180mcu_osu_sc_9T_clkinv_1 U281 (.Y(resp_msg[7]),
	.A(\intadd_1/SUM[6] ));
   gf180mcu_osu_sc_9T_clkinv_1 U282 (.Y(resp_msg[6]),
	.A(\intadd_1/SUM[5] ));
   gf180mcu_osu_sc_9T_clkinv_1 U283 (.Y(resp_msg[5]),
	.A(\intadd_1/SUM[4] ));
   gf180mcu_osu_sc_9T_clkinv_1 U284 (.Y(resp_msg[4]),
	.A(\intadd_1/SUM[3] ));
   gf180mcu_osu_sc_9T_clkinv_1 U285 (.Y(resp_msg[3]),
	.A(\intadd_1/SUM[2] ));
   gf180mcu_osu_sc_9T_clkinv_1 U286 (.Y(resp_msg[2]),
	.A(\intadd_1/SUM[1] ));
   gf180mcu_osu_sc_9T_clkinv_1 U287 (.Y(resp_msg[1]),
	.A(\intadd_1/SUM[0] ));
   gf180mcu_osu_sc_9T_addh_1 U288 (.CO(),
	.S(resp_msg[0]),
	.A(b_reg$out[0]),
	.B(a_reg$out[0]));
   gf180mcu_osu_sc_9T_aoi21_1 U289 (.Y(n286),
	.A0(n244),
	.A1(n285),
	.B(reset));
   gf180mcu_osu_sc_9T_clkinv_1 U290 (.Y(n287),
	.A(n286));
   gf180mcu_osu_sc_9T_aoi21_1 U291 (.Y(N45),
	.A0(resp_val),
	.A1(resp_rdy),
	.B(n287));
   gf180mcu_osu_sc_9T_clkinv_1 U292 (.Y(n289),
	.A(n288));
   gf180mcu_osu_sc_9T_nand2_1 U293 (.Y(n377),
	.A(n290),
	.B(n289));
   gf180mcu_osu_sc_9T_oai21_1 U294 (.Y(n291),
	.A0(n242),
	.A1(n290),
	.B(n244));
   gf180mcu_osu_sc_9T_addh_1 U295 (.CO(n292),
	.S(),
	.A(b_reg$out[15]),
	.B(n291));
   gf180mcu_osu_sc_9T_aoi21_1 U296 (.Y(n293),
	.A0(req_msg[15]),
	.A1(req_rdy),
	.B(n292));
   gf180mcu_osu_sc_9T_oai21_1 U297 (.Y(n224),
	.A0(n243),
	.A1(n377),
	.B(n293));
   gf180mcu_osu_sc_9T_addh_1 U298 (.CO(n294),
	.S(),
	.A(b_reg$out[14]),
	.B(n291));
   gf180mcu_osu_sc_9T_aoi21_1 U299 (.Y(n295),
	.A0(req_msg[14]),
	.A1(req_rdy),
	.B(n294));
   gf180mcu_osu_sc_9T_oai21_1 U300 (.Y(n223),
	.A0(n226),
	.A1(n377),
	.B(n295));
   gf180mcu_osu_sc_9T_addh_1 U301 (.CO(n296),
	.S(),
	.A(b_reg$out[1]),
	.B(n291));
   gf180mcu_osu_sc_9T_aoi21_1 U302 (.Y(n297),
	.A0(req_msg[1]),
	.A1(req_rdy),
	.B(n296));
   gf180mcu_osu_sc_9T_oai21_1 U303 (.Y(n222),
	.A0(n377),
	.A1(n227),
	.B(n297));
   gf180mcu_osu_sc_9T_addh_1 U304 (.CO(n299),
	.S(),
	.A(b_reg$out[2]),
	.B(n291));
   gf180mcu_osu_sc_9T_aoi21_1 U305 (.Y(n300),
	.A0(req_msg[2]),
	.A1(req_rdy),
	.B(n299));
   gf180mcu_osu_sc_9T_oai21_1 U306 (.Y(n221),
	.A0(n377),
	.A1(n238),
	.B(n300));
   gf180mcu_osu_sc_9T_addh_1 U307 (.CO(n301),
	.S(),
	.A(b_reg$out[3]),
	.B(n291));
   gf180mcu_osu_sc_9T_aoi21_1 U308 (.Y(n302),
	.A0(req_msg[3]),
	.A1(req_rdy),
	.B(n301));
   gf180mcu_osu_sc_9T_oai21_1 U309 (.Y(n220),
	.A0(n377),
	.A1(n240),
	.B(n302));
   gf180mcu_osu_sc_9T_addh_1 U310 (.CO(n303),
	.S(),
	.A(b_reg$out[4]),
	.B(n291));
   gf180mcu_osu_sc_9T_aoi21_1 U311 (.Y(n304),
	.A0(req_msg[4]),
	.A1(req_rdy),
	.B(n303));
   gf180mcu_osu_sc_9T_oai21_1 U312 (.Y(n219),
	.A0(n377),
	.A1(n228),
	.B(n304));
   gf180mcu_osu_sc_9T_addh_1 U313 (.CO(n305),
	.S(),
	.A(b_reg$out[5]),
	.B(n291));
   gf180mcu_osu_sc_9T_aoi21_1 U314 (.Y(n306),
	.A0(req_msg[5]),
	.A1(req_rdy),
	.B(n305));
   gf180mcu_osu_sc_9T_oai21_1 U315 (.Y(n218),
	.A0(n377),
	.A1(n231),
	.B(n306));
   gf180mcu_osu_sc_9T_addh_1 U316 (.CO(n307),
	.S(),
	.A(b_reg$out[6]),
	.B(n291));
   gf180mcu_osu_sc_9T_aoi21_1 U317 (.Y(n308),
	.A0(req_msg[6]),
	.A1(req_rdy),
	.B(n307));
   gf180mcu_osu_sc_9T_oai21_1 U318 (.Y(n217),
	.A0(n377),
	.A1(n233),
	.B(n308));
   gf180mcu_osu_sc_9T_addh_1 U319 (.CO(n309),
	.S(),
	.A(b_reg$out[7]),
	.B(n291));
   gf180mcu_osu_sc_9T_aoi21_1 U320 (.Y(n310),
	.A0(req_msg[7]),
	.A1(req_rdy),
	.B(n309));
   gf180mcu_osu_sc_9T_oai21_1 U321 (.Y(n216),
	.A0(n377),
	.A1(n234),
	.B(n310));
   gf180mcu_osu_sc_9T_addh_1 U322 (.CO(n311),
	.S(),
	.A(b_reg$out[8]),
	.B(n291));
   gf180mcu_osu_sc_9T_aoi21_1 U323 (.Y(n312),
	.A0(req_msg[8]),
	.A1(req_rdy),
	.B(n311));
   gf180mcu_osu_sc_9T_oai21_1 U324 (.Y(n215),
	.A0(n239),
	.A1(n377),
	.B(n312));
   gf180mcu_osu_sc_9T_addh_1 U325 (.CO(n313),
	.S(),
	.A(b_reg$out[9]),
	.B(n291));
   gf180mcu_osu_sc_9T_aoi21_1 U326 (.Y(n314),
	.A0(req_msg[9]),
	.A1(req_rdy),
	.B(n313));
   gf180mcu_osu_sc_9T_oai21_1 U327 (.Y(n214),
	.A0(n237),
	.A1(n377),
	.B(n314));
   gf180mcu_osu_sc_9T_addh_1 U328 (.CO(n315),
	.S(),
	.A(b_reg$out[10]),
	.B(n291));
   gf180mcu_osu_sc_9T_aoi21_1 U329 (.Y(n316),
	.A0(req_msg[10]),
	.A1(req_rdy),
	.B(n315));
   gf180mcu_osu_sc_9T_oai21_1 U330 (.Y(n213),
	.A0(n236),
	.A1(n377),
	.B(n316));
   gf180mcu_osu_sc_9T_addh_1 U331 (.CO(n317),
	.S(),
	.A(b_reg$out[11]),
	.B(n291));
   gf180mcu_osu_sc_9T_aoi21_1 U332 (.Y(n318),
	.A0(req_msg[11]),
	.A1(req_rdy),
	.B(n317));
   gf180mcu_osu_sc_9T_oai21_1 U333 (.Y(n212),
	.A0(n235),
	.A1(n377),
	.B(n318));
   gf180mcu_osu_sc_9T_addh_1 U334 (.CO(n319),
	.S(),
	.A(b_reg$out[12]),
	.B(n291));
   gf180mcu_osu_sc_9T_aoi21_1 U335 (.Y(n320),
	.A0(req_msg[12]),
	.A1(req_rdy),
	.B(n319));
   gf180mcu_osu_sc_9T_oai21_1 U336 (.Y(n211),
	.A0(n241),
	.A1(n377),
	.B(n320));
   gf180mcu_osu_sc_9T_addh_1 U337 (.CO(n321),
	.S(),
	.A(b_reg$out[13]),
	.B(n291));
   gf180mcu_osu_sc_9T_aoi21_1 U338 (.Y(n322),
	.A0(req_msg[13]),
	.A1(req_rdy),
	.B(n321));
   gf180mcu_osu_sc_9T_oai21_1 U339 (.Y(n210),
	.A0(n230),
	.A1(n377),
	.B(n322));
   gf180mcu_osu_sc_9T_addh_1 U340 (.CO(n323),
	.S(),
	.A(b_reg$out[0]),
	.B(n291));
   gf180mcu_osu_sc_9T_aoi21_1 U341 (.Y(n324),
	.A0(req_msg[0]),
	.A1(req_rdy),
	.B(n323));
   gf180mcu_osu_sc_9T_oai21_1 U342 (.Y(n209),
	.A0(n232),
	.A1(n377),
	.B(n324));
   gf180mcu_osu_sc_9T_nand2_1 U343 (.Y(n325),
	.A(req_msg[30]),
	.B(req_rdy));
   gf180mcu_osu_sc_9T_oai21_1 U344 (.Y(n326),
	.A0(n249),
	.A1(n377),
	.B(n325));
   gf180mcu_osu_sc_9T_aoi21_1 U345 (.Y(n327),
	.A0(state$out[1]),
	.A1(a_reg$out[14]),
	.B(n326));
   gf180mcu_osu_sc_9T_oai21_1 U346 (.Y(n208),
	.A0(\intadd_0/SUM[6] ),
	.A1(n271),
	.B(n327));
   gf180mcu_osu_sc_9T_clkinv_1 U347 (.Y(n328),
	.A(n377));
   gf180mcu_osu_sc_9T_addh_1 U348 (.CO(n329),
	.S(),
	.A(req_msg[17]),
	.B(req_rdy));
   gf180mcu_osu_sc_9T_aoi21_1 U349 (.Y(n330),
	.A0(b_reg$out[1]),
	.A1(n328),
	.B(n329));
   gf180mcu_osu_sc_9T_clkinv_1 U350 (.Y(n331),
	.A(n330));
   gf180mcu_osu_sc_9T_aoi21_1 U351 (.Y(n332),
	.A0(state$out[1]),
	.A1(a_reg$out[1]),
	.B(n331));
   gf180mcu_osu_sc_9T_oai21_1 U352 (.Y(n207),
	.A0(\intadd_1/SUM[0] ),
	.A1(n271),
	.B(n332));
   gf180mcu_osu_sc_9T_addh_1 U353 (.CO(n333),
	.S(),
	.A(req_msg[18]),
	.B(req_rdy));
   gf180mcu_osu_sc_9T_aoi21_1 U354 (.Y(n334),
	.A0(b_reg$out[2]),
	.A1(n328),
	.B(n333));
   gf180mcu_osu_sc_9T_clkinv_1 U355 (.Y(n335),
	.A(n334));
   gf180mcu_osu_sc_9T_aoi21_1 U356 (.Y(n336),
	.A0(state$out[1]),
	.A1(a_reg$out[2]),
	.B(n335));
   gf180mcu_osu_sc_9T_oai21_1 U357 (.Y(n206),
	.A0(\intadd_1/SUM[1] ),
	.A1(n271),
	.B(n336));
   gf180mcu_osu_sc_9T_addh_1 U358 (.CO(n337),
	.S(),
	.A(req_msg[19]),
	.B(req_rdy));
   gf180mcu_osu_sc_9T_aoi21_1 U359 (.Y(n338),
	.A0(b_reg$out[3]),
	.A1(n328),
	.B(n337));
   gf180mcu_osu_sc_9T_clkinv_1 U360 (.Y(n339),
	.A(n338));
   gf180mcu_osu_sc_9T_aoi21_1 U361 (.Y(n340),
	.A0(state$out[1]),
	.A1(a_reg$out[3]),
	.B(n339));
   gf180mcu_osu_sc_9T_oai21_1 U362 (.Y(n205),
	.A0(\intadd_1/SUM[2] ),
	.A1(n271),
	.B(n340));
   gf180mcu_osu_sc_9T_addh_1 U363 (.CO(n341),
	.S(),
	.A(req_msg[20]),
	.B(req_rdy));
   gf180mcu_osu_sc_9T_aoi21_1 U364 (.Y(n342),
	.A0(b_reg$out[4]),
	.A1(n328),
	.B(n341));
   gf180mcu_osu_sc_9T_clkinv_1 U365 (.Y(n343),
	.A(n342));
   gf180mcu_osu_sc_9T_aoi21_1 U366 (.Y(n344),
	.A0(state$out[1]),
	.A1(a_reg$out[4]),
	.B(n343));
   gf180mcu_osu_sc_9T_oai21_1 U367 (.Y(n204),
	.A0(\intadd_1/SUM[3] ),
	.A1(n271),
	.B(n344));
   gf180mcu_osu_sc_9T_addh_1 U368 (.CO(n345),
	.S(),
	.A(req_msg[21]),
	.B(req_rdy));
   gf180mcu_osu_sc_9T_aoi21_1 U369 (.Y(n346),
	.A0(b_reg$out[5]),
	.A1(n328),
	.B(n345));
   gf180mcu_osu_sc_9T_clkinv_1 U370 (.Y(n347),
	.A(n346));
   gf180mcu_osu_sc_9T_aoi21_1 U371 (.Y(n348),
	.A0(state$out[1]),
	.A1(a_reg$out[5]),
	.B(n347));
   gf180mcu_osu_sc_9T_oai21_1 U372 (.Y(n203),
	.A0(\intadd_1/SUM[4] ),
	.A1(n271),
	.B(n348));
   gf180mcu_osu_sc_9T_addh_1 U373 (.CO(n349),
	.S(),
	.A(req_msg[22]),
	.B(req_rdy));
   gf180mcu_osu_sc_9T_aoi21_1 U374 (.Y(n350),
	.A0(b_reg$out[6]),
	.A1(n328),
	.B(n349));
   gf180mcu_osu_sc_9T_clkinv_1 U375 (.Y(n351),
	.A(n350));
   gf180mcu_osu_sc_9T_aoi21_1 U376 (.Y(n352),
	.A0(state$out[1]),
	.A1(a_reg$out[6]),
	.B(n351));
   gf180mcu_osu_sc_9T_oai21_1 U377 (.Y(n202),
	.A0(\intadd_1/SUM[5] ),
	.A1(n271),
	.B(n352));
   gf180mcu_osu_sc_9T_addh_1 U378 (.CO(n353),
	.S(),
	.A(req_msg[23]),
	.B(req_rdy));
   gf180mcu_osu_sc_9T_aoi21_1 U379 (.Y(n354),
	.A0(b_reg$out[7]),
	.A1(n328),
	.B(n353));
   gf180mcu_osu_sc_9T_clkinv_1 U380 (.Y(n355),
	.A(n354));
   gf180mcu_osu_sc_9T_aoi21_1 U381 (.Y(n356),
	.A0(state$out[1]),
	.A1(a_reg$out[7]),
	.B(n355));
   gf180mcu_osu_sc_9T_oai21_1 U382 (.Y(n201),
	.A0(\intadd_1/SUM[6] ),
	.A1(n271),
	.B(n356));
   gf180mcu_osu_sc_9T_addh_1 U383 (.CO(n357),
	.S(),
	.A(req_msg[24]),
	.B(req_rdy));
   gf180mcu_osu_sc_9T_aoi21_1 U384 (.Y(n358),
	.A0(b_reg$out[8]),
	.A1(n328),
	.B(n357));
   gf180mcu_osu_sc_9T_clkinv_1 U385 (.Y(n359),
	.A(n358));
   gf180mcu_osu_sc_9T_aoi21_1 U386 (.Y(n360),
	.A0(state$out[1]),
	.A1(a_reg$out[8]),
	.B(n359));
   gf180mcu_osu_sc_9T_oai21_1 U387 (.Y(n200),
	.A0(\intadd_0/SUM[0] ),
	.A1(n271),
	.B(n360));
   gf180mcu_osu_sc_9T_addh_1 U388 (.CO(n361),
	.S(),
	.A(req_msg[25]),
	.B(req_rdy));
   gf180mcu_osu_sc_9T_aoi21_1 U389 (.Y(n362),
	.A0(b_reg$out[9]),
	.A1(n328),
	.B(n361));
   gf180mcu_osu_sc_9T_clkinv_1 U390 (.Y(n363),
	.A(n362));
   gf180mcu_osu_sc_9T_aoi21_1 U391 (.Y(n364),
	.A0(state$out[1]),
	.A1(a_reg$out[9]),
	.B(n363));
   gf180mcu_osu_sc_9T_oai21_1 U392 (.Y(n199),
	.A0(\intadd_0/SUM[1] ),
	.A1(n271),
	.B(n364));
   gf180mcu_osu_sc_9T_addh_1 U393 (.CO(n365),
	.S(),
	.A(req_msg[26]),
	.B(req_rdy));
   gf180mcu_osu_sc_9T_aoi21_1 U394 (.Y(n366),
	.A0(b_reg$out[10]),
	.A1(n328),
	.B(n365));
   gf180mcu_osu_sc_9T_clkinv_1 U395 (.Y(n367),
	.A(n366));
   gf180mcu_osu_sc_9T_aoi21_1 U396 (.Y(n368),
	.A0(state$out[1]),
	.A1(a_reg$out[10]),
	.B(n367));
   gf180mcu_osu_sc_9T_oai21_1 U397 (.Y(n198),
	.A0(\intadd_0/SUM[2] ),
	.A1(n271),
	.B(n368));
   gf180mcu_osu_sc_9T_nand2_1 U398 (.Y(n369),
	.A(req_msg[27]),
	.B(req_rdy));
   gf180mcu_osu_sc_9T_oai21_1 U399 (.Y(n370),
	.A0(n248),
	.A1(n377),
	.B(n369));
   gf180mcu_osu_sc_9T_aoi21_1 U400 (.Y(n371),
	.A0(state$out[1]),
	.A1(a_reg$out[11]),
	.B(n370));
   gf180mcu_osu_sc_9T_oai21_1 U401 (.Y(n197),
	.A0(\intadd_0/SUM[3] ),
	.A1(n271),
	.B(n371));
   gf180mcu_osu_sc_9T_addh_1 U402 (.CO(n372),
	.S(),
	.A(req_msg[28]),
	.B(req_rdy));
   gf180mcu_osu_sc_9T_aoi21_1 U403 (.Y(n373),
	.A0(b_reg$out[12]),
	.A1(n328),
	.B(n372));
   gf180mcu_osu_sc_9T_clkinv_1 U404 (.Y(n374),
	.A(n373));
   gf180mcu_osu_sc_9T_aoi21_1 U405 (.Y(n375),
	.A0(state$out[1]),
	.A1(a_reg$out[12]),
	.B(n374));
   gf180mcu_osu_sc_9T_oai21_1 U406 (.Y(n196),
	.A0(\intadd_0/SUM[4] ),
	.A1(n271),
	.B(n375));
   gf180mcu_osu_sc_9T_nand2_1 U407 (.Y(n376),
	.A(req_msg[29]),
	.B(req_rdy));
   gf180mcu_osu_sc_9T_oai21_1 U408 (.Y(n378),
	.A0(n246),
	.A1(n377),
	.B(n376));
   gf180mcu_osu_sc_9T_aoi21_1 U409 (.Y(n379),
	.A0(state$out[1]),
	.A1(a_reg$out[13]),
	.B(n378));
   gf180mcu_osu_sc_9T_oai21_1 U410 (.Y(n195),
	.A0(\intadd_0/SUM[5] ),
	.A1(n271),
	.B(n379));
   gf180mcu_osu_sc_9T_aoi21_1 U411 (.Y(n381),
	.A0(n244),
	.A1(n380),
	.B(n232));
   gf180mcu_osu_sc_9T_aoi21_1 U412 (.Y(n382),
	.A0(n328),
	.A1(b_reg$out[0]),
	.B(n381));
   gf180mcu_osu_sc_9T_clkinv_1 U413 (.Y(n383),
	.A(n382));
   gf180mcu_osu_sc_9T_aoi21_1 U414 (.Y(n384),
	.A0(req_rdy),
	.A1(req_msg[16]),
	.B(n383));
   gf180mcu_osu_sc_9T_oai21_1 U415 (.Y(n194),
	.A0(n271),
	.A1(n283),
	.B(n384));
   gf180mcu_osu_sc_9T_clkinv_1 U416 (.Y(n387),
	.A(resp_msg[15]));
   gf180mcu_osu_sc_9T_addh_1 U417 (.CO(n385),
	.S(),
	.A(req_msg[31]),
	.B(req_rdy));
   gf180mcu_osu_sc_9T_aoi21_1 U418 (.Y(n386),
	.A0(b_reg$out[15]),
	.A1(n328),
	.B(n385));
   gf180mcu_osu_sc_9T_oai21_1 U419 (.Y(n388),
	.A0(n271),
	.A1(n387),
	.B(n386));
   gf180mcu_osu_sc_9T_aoi21_1 U420 (.Y(n389),
	.A0(state$out[1]),
	.A1(a_reg$out[15]),
	.B(n388));
   gf180mcu_osu_sc_9T_clkinv_1 U421 (.Y(n193),
	.A(n389));
endmodule

