#!/bin/csh -f

################################################################################
#
# -------------------------------------
# Master EXT/Quantus compilation script
# -------------------------------------
#
# Compiles and creates the necessary EXT/Quantusa files for all the parasitic
# extraction corners
#
################################################################################

compile hrhc
compile hrlc
compile typical
compile lrhc
compile lrlc
echo ""
echo "All extraction corners compiled, generated and completed."
echo ""
