/*
###############################################################
#  Generated by:      Cadence Innovus 21.16-s078_1
#  OS:                Linux x86_64(Host ID yukari.ecen.okstate.edu)
#  Generated on:      Thu Apr 10 15:18:23 2025
#  Design:            fsm
#  Command:           saveNetlist -excludeLeafCell final.v
###############################################################
*/
module fsm (
	done, 
	load_rega, 
	load_regb, 
	load_regc, 
	load_regd, 
	load_regr, 
	load_regs, 
	sel_muxa, 
	sel_muxb, 
	sel_muxr, 
	clk, 
	reset, 
	start, 
	error, 
	op_type);
   output done;
   output load_rega;
   output load_regb;
   output load_regc;
   output load_regd;
   output load_regr;
   output load_regs;
   output [2:0] sel_muxa;
   output [2:0] sel_muxb;
   output sel_muxr;
   input clk;
   input reset;
   input start;
   input error;
   input op_type;

   // Internal wires
   wire N32;
   wire N33;
   wire N34;
   wire N35;
   wire N36;
   wire n88;
   wire n89;
   wire n90;
   wire n91;
   wire n92;
   wire n93;
   wire n94;
   wire n95;
   wire n96;
   wire n97;
   wire n98;
   wire n99;
   wire n100;
   wire n101;
   wire n102;
   wire n103;
   wire n104;
   wire n105;
   wire n106;
   wire n107;
   wire n108;
   wire n109;
   wire n110;
   wire n111;
   wire n112;
   wire n113;
   wire n114;
   wire n115;
   wire n116;
   wire n117;
   wire n118;
   wire n119;
   wire n120;
   wire n121;
   wire n122;
   wire n123;
   wire n124;
   wire n125;
   wire n126;
   wire n127;
   wire n128;
   wire n129;
   wire n130;
   wire n131;
   wire n132;
   wire n133;
   wire n134;
   wire n135;
   wire n136;
   wire n137;
   wire n138;
   wire n139;
   wire n140;
   wire n141;
   wire n142;
   wire n143;
   wire n144;
   wire n145;
   wire n146;
   wire n147;
   wire n148;
   wire n149;
   wire n150;
   wire n151;
   wire n152;
   wire n153;
   wire n154;
   wire n155;
   wire n156;
   wire n157;
   wire n158;
   wire n159;
   wire n160;
   wire n161;
   wire n162;
   wire n163;
   wire n164;
   wire n165;
   wire n166;
   wire n167;
   wire n168;
   wire n169;
   wire n170;
   wire n171;
   wire n172;
   wire n175;
   wire n176;
   wire n177;
   wire n178;
   wire n179;
   wire [4:0] state;

   assign sel_muxr = load_regr ;
   assign load_regc = load_rega ;

   DFFX1 \state_reg[1]  (.Q(state[1]),
	.QN(n178),
	.CLK(clk),
	.D(N33));
   DFFX1 \state_reg[4]  (.Q(state[4]),
	.QN(n179),
	.CLK(clk),
	.D(N36));
   DFFX1 \state_reg[0]  (.Q(state[0]),
	.QN(n176),
	.CLK(clk),
	.D(N32));
   DFFX1 \state_reg[2]  (.Q(state[2]),
	.QN(n175),
	.CLK(clk),
	.D(N34));
   DFFX1 \state_reg[3]  (.Q(state[3]),
	.QN(n177),
	.CLK(clk),
	.D(N35));
   NOR2X1 U107 (.Y(n164),
	.A(n177),
	.B(state[2]));
   NOR2X1 U108 (.Y(n144),
	.A(n176),
	.B(state[1]));
   NAND2X1 U109 (.Y(n147),
	.A(n164),
	.B(n144));
   INVX1 U110 (.Y(load_regr),
	.A(n147));
   NAND2X1 U112 (.Y(n131),
	.A(n176),
	.B(n178));
   INVX1 U113 (.Y(n130),
	.A(n131));
   NOR2X1 U114 (.Y(n88),
	.A(n176),
	.B(n178));
   NOR2X1 U115 (.Y(n154),
	.A(n130),
	.B(n88));
   NOR2X1 U116 (.Y(n121),
	.A(n154),
	.B(n179));
   NAND2X1 U117 (.Y(n160),
	.A(state[2]),
	.B(n177));
   INVX1 U118 (.Y(n143),
	.A(n160));
   NAND2X1 U119 (.Y(n90),
	.A(n121),
	.B(n143));
   NAND2X1 U120 (.Y(n115),
	.A(state[4]),
	.B(n144));
   INVX1 U121 (.Y(n106),
	.A(n115));
   NAND2X1 U122 (.Y(n141),
	.A(n175),
	.B(n177));
   INVX1 U123 (.Y(n149),
	.A(n141));
   NAND2X1 U124 (.Y(n89),
	.A(n106),
	.B(n149));
   NAND2X1 U125 (.Y(sel_muxa[2]),
	.A(n90),
	.B(n89));
   INVX1 U126 (.Y(n92),
	.A(sel_muxa[2]));
   NOR2X1 U127 (.Y(n129),
	.A(state[0]),
	.B(n178));
   AND3X1 U128 (.Y(n155),
	.A(state[2]),
	.B(state[3]),
	.C(n179));
   NAND2X1 U129 (.Y(n137),
	.A(n129),
	.B(n155));
   NAND3X1 U130 (.Y(n91),
	.A(state[0]),
	.B(n179),
	.C(n177));
   NAND3X1 U131 (.Y(load_rega),
	.A(n92),
	.B(n137),
	.C(n91));
   NAND2X1 U133 (.Y(n169),
	.A(n175),
	.B(n178));
   INVX1 U134 (.Y(n111),
	.A(start));
   NOR2X1 U135 (.Y(n93),
	.A(n111),
	.B(op_type));
   NOR2X1 U136 (.Y(n94),
	.A(n169),
	.B(n93));
   NAND2X1 U137 (.Y(n116),
	.A(n179),
	.B(n176));
   NOR2X1 U138 (.Y(n95),
	.A(n94),
	.B(n116));
   NAND2X1 U139 (.Y(n109),
	.A(n95),
	.B(n177));
   NAND2X1 U140 (.Y(n114),
	.A(state[0]),
	.B(n155));
   NAND2X1 U141 (.Y(n97),
	.A(n143),
	.B(n154));
   OR2X1 U142 (.Y(n96),
	.A(n141),
	.B(n144));
   NAND2X1 U143 (.Y(n98),
	.A(n97),
	.B(n96));
   NAND2X1 U144 (.Y(n99),
	.A(state[4]),
	.B(n98));
   NAND3X1 U145 (.Y(sel_muxb[0]),
	.A(n109),
	.B(n114),
	.C(n99));
   NAND2X1 U146 (.Y(n102),
	.A(n177),
	.B(n169));
   NAND2X1 U147 (.Y(n140),
	.A(state[4]),
	.B(n177));
   OR2X1 U148 (.Y(n127),
	.A(n178),
	.B(n114));
   NAND2X1 U149 (.Y(n171),
	.A(n140),
	.B(n127));
   INVX1 U150 (.Y(n101),
	.A(n171));
   NAND2X1 U151 (.Y(n100),
	.A(n106),
	.B(n175));
   NAND3X1 U152 (.Y(sel_muxb[1]),
	.A(n102),
	.B(n101),
	.C(n100));
   NAND2X1 U153 (.Y(n103),
	.A(state[4]),
	.B(load_regr));
   NAND2X1 U154 (.Y(sel_muxb[2]),
	.A(n137),
	.B(n103));
   NAND2X1 U155 (.Y(n104),
	.A(n149),
	.B(n129));
   NAND2X1 U156 (.Y(n110),
	.A(n104),
	.B(n103));
   INVX1 U157 (.Y(n139),
	.A(n155));
   NOR2X1 U158 (.Y(n105),
	.A(n178),
	.B(n139));
   NOR2X1 U159 (.Y(n108),
	.A(n110),
	.B(n105));
   NAND2X1 U160 (.Y(n107),
	.A(n143),
	.B(n106));
   NAND3X1 U161 (.Y(sel_muxa[0]),
	.A(n109),
	.B(n108),
	.C(n107));
   INVX1 U162 (.Y(n119),
	.A(n110));
   NOR2X1 U163 (.Y(n150),
	.A(n116),
	.B(n111));
   NAND3X1 U164 (.Y(n113),
	.A(n150),
	.B(op_type),
	.C(n177));
   NAND3X1 U165 (.Y(n112),
	.A(n149),
	.B(n144),
	.C(n179));
   AND3X1 U166 (.Y(n118),
	.A(n114),
	.B(n113),
	.C(n112));
   NAND2X1 U167 (.Y(n117),
	.A(n116),
	.B(n115));
   NAND2X1 U168 (.Y(n126),
	.A(n143),
	.B(n117));
   NAND3X1 U169 (.Y(sel_muxa[1]),
	.A(n119),
	.B(n118),
	.C(n126));
   NAND2X1 U170 (.Y(n151),
	.A(state[4]),
	.B(n176));
   INVX1 U171 (.Y(n120),
	.A(n151));
   NAND3X1 U172 (.Y(n124),
	.A(state[1]),
	.B(n143),
	.C(n120));
   NAND2X1 U173 (.Y(n123),
	.A(n155),
	.B(n144));
   NAND2X1 U174 (.Y(n122),
	.A(n121),
	.B(n149));
   NAND3X1 U175 (.Y(load_regd),
	.A(n124),
	.B(n123),
	.C(n122));
   NOR2X1 U176 (.Y(n125),
	.A(n150),
	.B(n129));
   NOR2X1 U177 (.Y(n133),
	.A(n141),
	.B(n125));
   INVX1 U178 (.Y(n128),
	.A(n133));
   NAND3X1 U179 (.Y(load_regb),
	.A(n128),
	.B(n127),
	.C(n126));
   AND2X1 U180 (.Y(done),
	.A(n129),
	.B(n164));
   AND2X1 U181 (.Y(load_regs),
	.A(n130),
	.B(n164));
   NOR2X1 U182 (.Y(n132),
	.A(n160),
	.B(n131));
   NOR2X1 U183 (.Y(n136),
	.A(n133),
	.B(n132));
   NOR2X1 U184 (.Y(n134),
	.A(n151),
	.B(state[3]));
   NOR2X1 U185 (.Y(n135),
	.A(load_regs),
	.B(n134));
   AND3X1 U186 (.Y(n138),
	.A(n137),
	.B(n136),
	.C(n135));
   NOR2X1 U187 (.Y(N32),
	.A(reset),
	.B(n138));
   NAND3X1 U188 (.Y(n142),
	.A(n141),
	.B(n140),
	.C(n139));
   NAND2X1 U189 (.Y(n146),
	.A(n154),
	.B(n142));
   NAND2X1 U190 (.Y(n145),
	.A(n144),
	.B(n143));
   AND3X1 U191 (.Y(n148),
	.A(n147),
	.B(n146),
	.C(n145));
   NOR2X1 U192 (.Y(N33),
	.A(reset),
	.B(n148));
   NAND3X1 U193 (.Y(n157),
	.A(state[0]),
	.B(n149),
	.C(state[1]));
   NAND3X1 U194 (.Y(n159),
	.A(n150),
	.B(op_type),
	.C(n178));
   NAND2X1 U195 (.Y(n161),
	.A(state[1]),
	.B(n151));
   NAND2X1 U196 (.Y(n152),
	.A(state[2]),
	.B(n161));
   NAND2X1 U197 (.Y(n153),
	.A(n159),
	.B(n152));
   NAND2X1 U198 (.Y(n156),
	.A(n177),
	.B(n153));
   NAND2X1 U199 (.Y(n167),
	.A(n155),
	.B(n154));
   AND3X1 U200 (.Y(n158),
	.A(n157),
	.B(n156),
	.C(n167));
   NOR2X1 U201 (.Y(N34),
	.A(reset),
	.B(n158));
   NOR2X1 U202 (.Y(n163),
	.A(n159),
	.B(state[2]));
   NOR2X1 U203 (.Y(n162),
	.A(n161),
	.B(n160));
   NOR2X1 U204 (.Y(n166),
	.A(n163),
	.B(n162));
   NAND2X1 U205 (.Y(n165),
	.A(n164),
	.B(n178));
   AND3X1 U206 (.Y(n168),
	.A(n167),
	.B(n166),
	.C(n165));
   NOR2X1 U207 (.Y(N35),
	.A(reset),
	.B(n168));
   NOR2X1 U208 (.Y(n170),
	.A(n179),
	.B(n169));
   NOR2X1 U209 (.Y(n172),
	.A(n171),
	.B(n170));
   NOR2X1 U210 (.Y(N36),
	.A(reset),
	.B(n172));
endmodule

