#!/bin/bash

mkdir -p ../.tmp
mv abstract_SKILL_script ../.tmp/
mv lef_gen ../.tmp/
mv clean_all ../.tmp/
mv Makefile ../.tmp/
mv adjust_lef.py ../.tmp/
mv extract_area_lef.py ../.tmp/
rm -rf ../abstract/*
rm -rf GDS 
rm -rf .cadence*
rm -rf .abstract*
mv ../.tmp/* .
rm -rf ../.tmp