#!/bin/csh -f

################################################################################
#
# -------------------------------------
# Master Calibre PEX compilation script
# -------------------------------------
#
# Compiles and creates the Calibre PEX rules.C and rules.R files for all the
# parasitic extraction corners
#
################################################################################

compile hrhc
compile hrlc
compile typical
compile lrhc
compile lrlc
echo ""
echo "All extraction corners compiled, generated and completed."
echo ""
