#!/bin/bash
export RUNSET_DIR=$(cd ./V2.1.302/PV/Calibre/PEX/; pwd)
export PDK_HOME=$(cd ./V2.1.302/; pwd)
export JOB_HOME=$(cd ../layout/$1/gds/; pwd)
export FILE_OUT=./output/
export PEX_PROCESS="Typical"
#export SOURCE_FILES=$(cd ./source_files/; pwd)
export SOURCE_FILES=$(cd ./$1/; pwd)
export LAYOUT_PATTERN="*ring_oscillator_mpr*"
export PWD=$(pwd)

export LOG
export JOB_NAME  
export JOB_HOME

echo -e "RUNSET_DIR=$RUNSET_DIR\nPDK_HOME=$PDK_HOME\nJOB_HOME=$JOB_HOME"

#Sets the LOG variable and creates the log directory if it doesn't exist.
if [ ! -d "$FILE_OUT/log" ]; then
    mkdir -p $FILE_OUT/log
    LOG=$FILE_OUT/log
else
    LOG=$FILE_OUT/log
fi

#Removes the outputs if the script is run again. Otherwise it creates the output directory and all of its subdirectories
if [ ! -d "$FILE_OUT" ]; then
    echo "Making output directory...."
    mkdir -p $FILE_OUT/{report,ext}
else
    echo "Building Directories...."
    mkdir -p $FILE_OUT/{report,ext}
fi

# If the input argument $1 doesn't exist, then it sets the input variable to all of the gds files in
# the JOB_HOME directory. Else, it assumes that the $1 input is the name of the gds file to be used.
#if [ ! -z "$1" ]; then
#	export i=$(echo $1 | cut -f 1 -d '.') #i is used as the input variable 
#else 
	export i="$(basename -s .gds $(ls $JOB_HOME/$LAYOUT_PATTERN))" #i is used as the input variable
#fi

#Loops through the input gds files. If no user input is supplied, all gds files are put through the PEX process. 
for JOB_NAME in $i ; do 
    #Checks to make sure the file supplied exists. If not, then it exits the bash script.
    if [ ! -e $JOB_HOME/$JOB_NAME.gds ]; then echo "Did not find '$JOB_HOME/$JOB_NAME'"
        exit 1
    fi

    echo -e "\nexport JOB_HOME='$JOB_HOME'"
    echo -e "export JOB_NAME='$JOB_NAME'"
    echo -e "====================================="

    set -x #Turns on debugging
    echo $PDK_HOME

    calibre -gui -pex -runset $RUNSET_DIR/s130_pex_runset_spef -batch > $LOG/s130_pex_runset.log 2>&1

    set +x #Turns off debugging
done #End of the loop

# The following sed lines make adjustments to the .spi files to ensure proper operation in liberate
# characterization. 

mkdir $FILE_OUT/spef
mkdir $FILE_OUT/report

mv *.spef $FILE_OUT/spef
mv *.report $FILE_OUT/report

echo "Moving output files to ./output"
mv -v *.ext $FILE_OUT/ext/
mv -fv svdb/ $FILE_OUT
mv -v _calibre_pex.rul_ $FILE_OUT/
mv -v _calibre_probe_file_ $FILE_OUT/
mv -v *.shorts $FILE_OUT/

exit 0
