set init_layout_view ""
set init_abstract_name ""
set init_verilog "/import/yukari1/lrburle/OSU_180/char/techfiles/gcd.vh"
set init_mmmc_file "/import/yukari1/lrburle/OSU_180/flow_cadence/pnr/FF/view_definition.tcl"
set init_lef_file "../../char/techfiles//gf180mcu_5LM_1TM_9K_9t_tech.lef ../../char/techfiles//gf180mcu_osu_sc_9T.lef"
set init_top_cell "gcd"
set init_gnd_net "VSS"
set init_pwr_net "VDD"
