###################################################################

# Created by write_sdc on Fri Mar  7 11:20:42 2025

###################################################################
set sdc_version 2.1

set_units -time ns -resistance kOhm -capacitance pF -voltage V -current mA
set_wire_load_mode top
set_driving_cell -lib_cell TMRDFFQX1 -pin Q [get_ports {op1[10]}]
set_driving_cell -lib_cell TMRDFFQX1 -pin Q [get_ports {op1[9]}]
set_driving_cell -lib_cell TMRDFFQX1 -pin Q [get_ports {op1[8]}]
set_driving_cell -lib_cell TMRDFFQX1 -pin Q [get_ports {op1[7]}]
set_driving_cell -lib_cell TMRDFFQX1 -pin Q [get_ports {op1[6]}]
set_driving_cell -lib_cell TMRDFFQX1 -pin Q [get_ports {op1[5]}]
set_driving_cell -lib_cell TMRDFFQX1 -pin Q [get_ports {op1[4]}]
set_driving_cell -lib_cell TMRDFFQX1 -pin Q [get_ports {op1[3]}]
set_driving_cell -lib_cell TMRDFFQX1 -pin Q [get_ports {op1[2]}]
set_driving_cell -lib_cell TMRDFFQX1 -pin Q [get_ports {op1[1]}]
set_driving_cell -lib_cell TMRDFFQX1 -pin Q [get_ports {op1[0]}]
set_driving_cell -lib_cell TMRDFFQX1 -pin Q [get_ports {op2[10]}]
set_driving_cell -lib_cell TMRDFFQX1 -pin Q [get_ports {op2[9]}]
set_driving_cell -lib_cell TMRDFFQX1 -pin Q [get_ports {op2[8]}]
set_driving_cell -lib_cell TMRDFFQX1 -pin Q [get_ports {op2[7]}]
set_driving_cell -lib_cell TMRDFFQX1 -pin Q [get_ports {op2[6]}]
set_driving_cell -lib_cell TMRDFFQX1 -pin Q [get_ports {op2[5]}]
set_driving_cell -lib_cell TMRDFFQX1 -pin Q [get_ports {op2[4]}]
set_driving_cell -lib_cell TMRDFFQX1 -pin Q [get_ports {op2[3]}]
set_driving_cell -lib_cell TMRDFFQX1 -pin Q [get_ports {op2[2]}]
set_driving_cell -lib_cell TMRDFFQX1 -pin Q [get_ports {op2[1]}]
set_driving_cell -lib_cell TMRDFFQX1 -pin Q [get_ports {op2[0]}]
set_load -pin_load 0.0403555 [get_ports {y[21]}]
set_load -pin_load 0.0403555 [get_ports {y[20]}]
set_load -pin_load 0.0403555 [get_ports {y[19]}]
set_load -pin_load 0.0403555 [get_ports {y[18]}]
set_load -pin_load 0.0403555 [get_ports {y[17]}]
set_load -pin_load 0.0403555 [get_ports {y[16]}]
set_load -pin_load 0.0403555 [get_ports {y[15]}]
set_load -pin_load 0.0403555 [get_ports {y[14]}]
set_load -pin_load 0.0403555 [get_ports {y[13]}]
set_load -pin_load 0.0403555 [get_ports {y[12]}]
set_load -pin_load 0.0403555 [get_ports {y[11]}]
set_load -pin_load 0.0403555 [get_ports {y[10]}]
set_load -pin_load 0.0403555 [get_ports {y[9]}]
set_load -pin_load 0.0403555 [get_ports {y[8]}]
set_load -pin_load 0.0403555 [get_ports {y[7]}]
set_load -pin_load 0.0403555 [get_ports {y[6]}]
set_load -pin_load 0.0403555 [get_ports {y[5]}]
set_load -pin_load 0.0403555 [get_ports {y[4]}]
set_load -pin_load 0.0403555 [get_ports {y[3]}]
set_load -pin_load 0.0403555 [get_ports {y[2]}]
set_load -pin_load 0.0403555 [get_ports {y[1]}]
set_load -pin_load 0.0403555 [get_ports {y[0]}]
set_max_fanout 6 [get_ports {op1[10]}]
set_max_fanout 6 [get_ports {op1[9]}]
set_max_fanout 6 [get_ports {op1[8]}]
set_max_fanout 6 [get_ports {op1[7]}]
set_max_fanout 6 [get_ports {op1[6]}]
set_max_fanout 6 [get_ports {op1[5]}]
set_max_fanout 6 [get_ports {op1[4]}]
set_max_fanout 6 [get_ports {op1[3]}]
set_max_fanout 6 [get_ports {op1[2]}]
set_max_fanout 6 [get_ports {op1[1]}]
set_max_fanout 6 [get_ports {op1[0]}]
set_max_fanout 6 [get_ports {op2[10]}]
set_max_fanout 6 [get_ports {op2[9]}]
set_max_fanout 6 [get_ports {op2[8]}]
set_max_fanout 6 [get_ports {op2[7]}]
set_max_fanout 6 [get_ports {op2[6]}]
set_max_fanout 6 [get_ports {op2[5]}]
set_max_fanout 6 [get_ports {op2[4]}]
set_max_fanout 6 [get_ports {op2[3]}]
set_max_fanout 6 [get_ports {op2[2]}]
set_max_fanout 6 [get_ports {op2[1]}]
set_max_fanout 6 [get_ports {op2[0]}]
create_clock [get_ports clk]  -period 2  -waveform {0 1}
set_clock_uncertainty 0.2  [get_clocks clk]
set_propagated_clock [get_clocks clk]
set_input_delay -clock clk  -max 0  [get_ports {op1[10]}]
set_input_delay -clock clk  -max 0  [get_ports {op1[9]}]
set_input_delay -clock clk  -max 0  [get_ports {op1[8]}]
set_input_delay -clock clk  -max 0  [get_ports {op1[7]}]
set_input_delay -clock clk  -max 0  [get_ports {op1[6]}]
set_input_delay -clock clk  -max 0  [get_ports {op1[5]}]
set_input_delay -clock clk  -max 0  [get_ports {op1[4]}]
set_input_delay -clock clk  -max 0  [get_ports {op1[3]}]
set_input_delay -clock clk  -max 0  [get_ports {op1[2]}]
set_input_delay -clock clk  -max 0  [get_ports {op1[1]}]
set_input_delay -clock clk  -max 0  [get_ports {op1[0]}]
set_input_delay -clock clk  -max 0  [get_ports {op2[10]}]
set_input_delay -clock clk  -max 0  [get_ports {op2[9]}]
set_input_delay -clock clk  -max 0  [get_ports {op2[8]}]
set_input_delay -clock clk  -max 0  [get_ports {op2[7]}]
set_input_delay -clock clk  -max 0  [get_ports {op2[6]}]
set_input_delay -clock clk  -max 0  [get_ports {op2[5]}]
set_input_delay -clock clk  -max 0  [get_ports {op2[4]}]
set_input_delay -clock clk  -max 0  [get_ports {op2[3]}]
set_input_delay -clock clk  -max 0  [get_ports {op2[2]}]
set_input_delay -clock clk  -max 0  [get_ports {op2[1]}]
set_input_delay -clock clk  -max 0  [get_ports {op2[0]}]
set_output_delay -clock clk  -max 0  [get_ports {y[21]}]
set_output_delay -clock clk  -max 0  [get_ports {y[20]}]
set_output_delay -clock clk  -max 0  [get_ports {y[19]}]
set_output_delay -clock clk  -max 0  [get_ports {y[18]}]
set_output_delay -clock clk  -max 0  [get_ports {y[17]}]
set_output_delay -clock clk  -max 0  [get_ports {y[16]}]
set_output_delay -clock clk  -max 0  [get_ports {y[15]}]
set_output_delay -clock clk  -max 0  [get_ports {y[14]}]
set_output_delay -clock clk  -max 0  [get_ports {y[13]}]
set_output_delay -clock clk  -max 0  [get_ports {y[12]}]
set_output_delay -clock clk  -max 0  [get_ports {y[11]}]
set_output_delay -clock clk  -max 0  [get_ports {y[10]}]
set_output_delay -clock clk  -max 0  [get_ports {y[9]}]
set_output_delay -clock clk  -max 0  [get_ports {y[8]}]
set_output_delay -clock clk  -max 0  [get_ports {y[7]}]
set_output_delay -clock clk  -max 0  [get_ports {y[6]}]
set_output_delay -clock clk  -max 0  [get_ports {y[5]}]
set_output_delay -clock clk  -max 0  [get_ports {y[4]}]
set_output_delay -clock clk  -max 0  [get_ports {y[3]}]
set_output_delay -clock clk  -max 0  [get_ports {y[2]}]
set_output_delay -clock clk  -max 0  [get_ports {y[1]}]
set_output_delay -clock clk  -max 0  [get_ports {y[0]}]
